language: go
go:
  - tip

notifications:
  email: false

before_script:
  - go get -t -v ./...
script:
  - go test -v ./weatherParser/
  - go test -v ./weatherLogin/
  - go build -v ./weatherParser/
  - go build -v ./weatherLogin/
