// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weather.proto

package weatherParse

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WeatherParams struct {
	MonthsNumbers        []int32  `protobuf:"varint,1,rep,packed,name=MonthsNumbers,proto3" json:"MonthsNumbers,omitempty"`
	Cities               []string `protobuf:"bytes,2,rep,name=Cities,proto3" json:"Cities,omitempty"`
	Site                 string   `protobuf:"bytes,3,opt,name=Site,proto3" json:"Site,omitempty"`
	Months               []string `protobuf:"bytes,4,rep,name=Months,proto3" json:"Months,omitempty"`
	Year                 string   `protobuf:"bytes,5,opt,name=Year,proto3" json:"Year,omitempty"`
	ReplyFormat          string   `protobuf:"bytes,6,opt,name=ReplyFormat,proto3" json:"ReplyFormat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeatherParams) Reset()         { *m = WeatherParams{} }
func (m *WeatherParams) String() string { return proto.CompactTextString(m) }
func (*WeatherParams) ProtoMessage()    {}
func (*WeatherParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{0}
}

func (m *WeatherParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherParams.Unmarshal(m, b)
}
func (m *WeatherParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherParams.Marshal(b, m, deterministic)
}
func (m *WeatherParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherParams.Merge(m, src)
}
func (m *WeatherParams) XXX_Size() int {
	return xxx_messageInfo_WeatherParams.Size(m)
}
func (m *WeatherParams) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherParams.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherParams proto.InternalMessageInfo

func (m *WeatherParams) GetMonthsNumbers() []int32 {
	if m != nil {
		return m.MonthsNumbers
	}
	return nil
}

func (m *WeatherParams) GetCities() []string {
	if m != nil {
		return m.Cities
	}
	return nil
}

func (m *WeatherParams) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *WeatherParams) GetMonths() []string {
	if m != nil {
		return m.Months
	}
	return nil
}

func (m *WeatherParams) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *WeatherParams) GetReplyFormat() string {
	if m != nil {
		return m.ReplyFormat
	}
	return ""
}

type DayWeather struct {
	ComparisonCSV        []byte   `protobuf:"bytes,1,opt,name=ComparisonCSV,proto3" json:"ComparisonCSV,omitempty"`
	Format               string   `protobuf:"bytes,2,opt,name=Format,proto3" json:"Format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DayWeather) Reset()         { *m = DayWeather{} }
func (m *DayWeather) String() string { return proto.CompactTextString(m) }
func (*DayWeather) ProtoMessage()    {}
func (*DayWeather) Descriptor() ([]byte, []int) {
	return fileDescriptor_231dcd72b885f4be, []int{1}
}

func (m *DayWeather) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DayWeather.Unmarshal(m, b)
}
func (m *DayWeather) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DayWeather.Marshal(b, m, deterministic)
}
func (m *DayWeather) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DayWeather.Merge(m, src)
}
func (m *DayWeather) XXX_Size() int {
	return xxx_messageInfo_DayWeather.Size(m)
}
func (m *DayWeather) XXX_DiscardUnknown() {
	xxx_messageInfo_DayWeather.DiscardUnknown(m)
}

var xxx_messageInfo_DayWeather proto.InternalMessageInfo

func (m *DayWeather) GetComparisonCSV() []byte {
	if m != nil {
		return m.ComparisonCSV
	}
	return nil
}

func (m *DayWeather) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func init() {
	proto.RegisterType((*WeatherParams)(nil), "weatherParse.WeatherParams")
	proto.RegisterType((*DayWeather)(nil), "weatherParse.DayWeather")
}

func init() { proto.RegisterFile("weather.proto", fileDescriptor_231dcd72b885f4be) }

var fileDescriptor_231dcd72b885f4be = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xcd, 0xfe, 0x29, 0x6c, 0xdc, 0x22, 0xe4, 0x20, 0x41, 0x11, 0x42, 0xf1, 0xd0, 0x53,
	0x0f, 0xfa, 0x11, 0x0a, 0x7a, 0x52, 0xcb, 0x2c, 0x28, 0x1e, 0xb3, 0xcb, 0xc0, 0x16, 0x6c, 0x53,
	0x67, 0xb2, 0x88, 0x9f, 0xca, 0xaf, 0x28, 0x49, 0xe3, 0xb2, 0x05, 0x6f, 0xf3, 0xde, 0xfc, 0x66,
	0x78, 0x3c, 0x99, 0x7f, 0xa1, 0xf5, 0x7b, 0xa4, 0x6a, 0x20, 0xe7, 0x9d, 0x5a, 0x27, 0xd9, 0x58,
	0x62, 0x2c, 0x7e, 0x84, 0xcc, 0xdf, 0x8e, 0x86, 0xed, 0x58, 0xdd, 0xca, 0xfc, 0xc9, 0xf5, 0x7e,
	0xcf, 0xcf, 0x87, 0x6e, 0x8b, 0xc4, 0x5a, 0x98, 0x79, 0xb9, 0x84, 0xa9, 0xa9, 0x2e, 0x65, 0x56,
	0xb7, 0xbe, 0x45, 0xd6, 0x33, 0x33, 0x2f, 0x57, 0x90, 0x94, 0x52, 0x72, 0xb1, 0x69, 0x3d, 0xea,
	0xb9, 0x11, 0xe5, 0x0a, 0xe2, 0x1c, 0xd8, 0xf1, 0x58, 0x2f, 0x46, 0x76, 0x54, 0x81, 0x7d, 0x47,
	0x4b, 0x7a, 0x39, 0xb2, 0x61, 0x56, 0x46, 0x9e, 0x03, 0x0e, 0x1f, 0xdf, 0x0f, 0x8e, 0x3a, 0xeb,
	0x75, 0x16, 0x57, 0xa7, 0x56, 0xf1, 0x22, 0x2f, 0x52, 0x60, 0x40, 0x1e, 0x5c, 0xcf, 0x18, 0x22,
	0xd7, 0xae, 0x1b, 0x2c, 0xb5, 0xec, 0xfa, 0x7a, 0xf3, 0xaa, 0x85, 0x11, 0xe5, 0x1a, 0xa6, 0x66,
	0x88, 0x91, 0xbe, 0xce, 0xe2, 0xd7, 0xa4, 0xee, 0x76, 0xc7, 0x86, 0x62, 0x25, 0xa4, 0x40, 0xaa,
	0x86, 0xdc, 0x0e, 0x99, 0x1f, 0xa1, 0xa9, 0x01, 0x3f, 0x0f, 0xc8, 0x5e, 0x5d, 0x57, 0xa7, 0x54,
	0x35, 0x29, 0xed, 0xea, 0xe6, 0xdf, 0xe5, 0x5f, 0xc0, 0xe2, 0x6c, 0x9b, 0xc5, 0xf2, 0xef, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x87, 0x59, 0x23, 0x34, 0x8d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WeatherParserClient is the client API for WeatherParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WeatherParserClient interface {
	ProcessGRPCRequest(ctx context.Context, in *WeatherParams, opts ...grpc.CallOption) (*DayWeather, error)
}

type weatherParserClient struct {
	cc *grpc.ClientConn
}

func NewWeatherParserClient(cc *grpc.ClientConn) WeatherParserClient {
	return &weatherParserClient{cc}
}

func (c *weatherParserClient) ProcessGRPCRequest(ctx context.Context, in *WeatherParams, opts ...grpc.CallOption) (*DayWeather, error) {
	out := new(DayWeather)
	err := c.cc.Invoke(ctx, "/weatherParse.weatherParser/ProcessGRPCRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherParserServer is the server API for WeatherParser service.
type WeatherParserServer interface {
	ProcessGRPCRequest(context.Context, *WeatherParams) (*DayWeather, error)
}

// UnimplementedWeatherParserServer can be embedded to have forward compatible implementations.
type UnimplementedWeatherParserServer struct {
}

func (*UnimplementedWeatherParserServer) ProcessGRPCRequest(ctx context.Context, req *WeatherParams) (*DayWeather, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessGRPCRequest not implemented")
}

func RegisterWeatherParserServer(s *grpc.Server, srv WeatherParserServer) {
	s.RegisterService(&_WeatherParser_serviceDesc, srv)
}

func _WeatherParser_ProcessGRPCRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherParserServer).ProcessGRPCRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weatherParse.weatherParser/ProcessGRPCRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherParserServer).ProcessGRPCRequest(ctx, req.(*WeatherParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _WeatherParser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "weatherParse.weatherParser",
	HandlerType: (*WeatherParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessGRPCRequest",
			Handler:    _WeatherParser_ProcessGRPCRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weather.proto",
}
